### PR TITLE
Updated dependencies, migrated to AndroidX and fixed tests

### LINKED ISSUE #228: Support for androidx

### PR DESCRIPTION
**Pull request by Rolf-Smit**
Fixes #228

Notes:

- Updated Butterknife and LeakCanary to their newest versions to support AndroidX.
- LeakCanary 2.x does not require additional setup nor a no-op: https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/
- Butterknife 10.x requires Java 8 source compatibility.
- It is no longer necessary to manually apply the `buildToolsVersion`, this is automatically done by the Android Gradle Plugin.

The old support libraries are by now stone age artifacts, and AndroidX really is the new standard. I hope this PR can be merged soon.

### CODE REVIEW

**Comment by Rolf-Smit** [comment]
@Serchinastico It seems the build server script failed because the new licenses are not accepted. Do you want me to update the script? Any chance you're still actively working on this?

File: dexter/src/main/java/com/karumi/dexter/DexterInstance.java [hunk 1]
```diff
@@ -166,7 +166,7 @@ void onCancelPermissionRequest() {
   private void requestPermissionsToSystem(Collection<String> permissions) {
     if (!isShowingNativeDialog.get()) {
       androidPermissionService.requestPermissions(activity,
-          permissions.toArray(new String[permissions.size()]), PERMISSIONS_REQUEST_CODE);
+          permissions.toArray(new String[0]), PERMISSIONS_REQUEST_CODE);
```
Comment (pedrovgs) [inline dexter/src/main/java/com/karumi/dexter/DexterInstance.java]: Why did you change this? If the array is not initialized with the expected size the code will not work.

File: build.gradle [hunk 2]
```diff
@@ -4,15 +4,14 @@ buildscript {
     jcenter()
   }
   dependencies {
-    classpath 'com.android.tools.build:gradle:3.1.3'
+    classpath 'com.android.tools.build:gradle:3.3.2'
```
Comment (pedrovgs) [inline build.gradle]: You'll have to update the CI script to install these dependencies.

**Comment by pedrovgs** [comment]
Thanks for your contribution @Rolf-Smit 😃 As you said before, you'll have to update the Travis-CI configuration to be able to use the expected dependencies. Please, update the ``travis.ci`` file and answer my question and I'll personally release a new version with these changes.

File: dexter/src/main/java/com/karumi/dexter/DexterInstance.java (hunk 1 above)
Comment (Rolf-Smit) [reply dexter/src/main/java/com/karumi/dexter/DexterInstance.java]: No the code wont break. This change was actually suggested by the IDEA. Numerous sources even claim that using array size 0 is faster than creating an array of the list size manually:

https://medium.com/@hanru.yeh/collection-toarray-new-t-0-will-be-faster-than-collection-toarray-new-t-size-5b129fabfa88

https://stackoverflow.com/questions/174093/toarraynew-myclass0-or-toarraynew-myclassmylist-size

File: build.gradle (hunk 2 above)
Comment (Rolf-Smit) [reply build.gradle]: I will try to update the script!

File: dexter/src/main/java/com/karumi/dexter/DexterInstance.java (hunk 1 above)
Comment (Rolf-Smit) [reply dexter/src/main/java/com/karumi/dexter/DexterInstance.java]: > There are two styles to convert a collection to an array: either using a pre-sized array (like c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
> 
> In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray call which may result in extra nulls at the end of the array, if the collection was concurrently shrunk during the operation.
> 
> This inspection allows to follow the uniform style: either using an empty array (which is recommended in modern Java) or using a pre-sized array (which might be faster in older Java versions or non-HotSpot based JVMs).

https://github.com/JetBrains/intellij-community/blob/master/plugins/InspectionGadgets/src/inspectionDescriptions/ToArrayCallWithZeroLengthArrayArgument.html

**Comment by Rolf-Smit** [comment]
@pedrovgs Thanks for your quick response, I fixed the Travis build and commented on the `toArray()` question.

File: dexter/src/main/java/com/karumi/dexter/DexterInstance.java (hunk 1 above)
Comment (pedrovgs) [reply dexter/src/main/java/com/karumi/dexter/DexterInstance.java]: Interesting!

**Comment by Rolf-Smit** [comment]
@pedrovgs any update on when this will be merged and when we can expect a new version :)
