### PR TITLE
Fix duplicated permission report

### LINKED ISSUE #270: Duplicate Permission in report
I have this code:
```
class PermissionsRepositoryImpl(
    private val permissionManager: DexterBuilder.Permission
) : PermissionsRepository {

    override fun isPhotoAccessPermissionEnabled(): Single<DomainMultiplePermissions> {
        return Single.create { single ->
            permissionManager
                .withPermissions(Manifest.permission.CAMERA, Manifest.permission.READ_EXTERNAL_STORAGE)
                .withListener(object: MultiplePermissionsListener {
                    override fun onPermissionsChecked(report: MultiplePermissionsReport?) {
                        when (report) {
                            null -> single.onError(DomainPermissionReportException(
                                DomainPermissionReportException.Error.REPORT_ERROR,
                                "Permission report is null"))
                            else -> single.onSuccess(report.toDomain())
                        }
                    }

                    override fun onPermissionRationaleShouldBeShown(permissions: List<PermissionRequest?>?, token: PermissionToken?) {
                        token?.continuePermissionRequest()
                    }
                })
                .check()
        }
    }
}
```

### Expected behaviour
The report should include just 2 grantedPermissions if i accept both.

### Actual behaviour
The report includes 3 grantedPermissions if i accept both.

### Steps to reproduce
I Call this code from a button from UI.
I accept first the READ_EXTERNAL_STORAGE permission and refuse once the CAMERA permission.
Then i re-tap the button to retrigger isPhotoAccessPermissionEnabled(). Only the popup for CAMERA is displayling but in the onPermissionsChecked callback, report.grantedPermissionResponse array size = 3 and READ_EXTERNAL_STORAGE appears twice.

### Version of the library
Last version

### PR DESCRIPTION
**Pull request by pedrovgs**
### :pushpin: References
* **Issue:** Fixes #270 

### :tophat: What is the goal?

Fix an error related to the permission reports being duplicated under some circumstances.

### :memo: How is it being implemented?

We've just updated ``MultiplePermissionsReport`` to use a ``Set`` instead of a ``List`` so we do not duplicate the reported permissions when handling the same set of permissions consecutively. Last but not least, we've added coverage.

### :robot: How can it be tested?

🤖

### CODE REVIEW

File: dexter/src/main/java/com/karumi/dexter/MultiplePermissionsReport.java [hunk 1]
```diff
@@ -18,34 +18,37 @@
...
-  private final List<PermissionGrantedResponse> grantedPermissionResponses;
-  private final List<PermissionDeniedResponse> deniedPermissionResponses;
+  private final Set<PermissionGrantedResponse> grantedPermissionResponses;
+  private final Set<PermissionDeniedResponse> deniedPermissionResponses;
 
   MultiplePermissionsReport() {
-    grantedPermissionResponses = new LinkedList<>();
-    deniedPermissionResponses = new LinkedList<>();
+    grantedPermissionResponses = new LinkedHashSet<>();
+    deniedPermissionResponses = new LinkedHashSet<>();
```
Comment (flipper83) [inline dexter/src/main/java/com/karumi/dexter/MultiplePermissionsReport.java:37]: my  only concern here is the LinkedHashSet keep the order. If doesn't maintain the order, I'd add a comment on the get method.

**Review by flipper83 — APPROVED** [review]

File: dexter/src/main/java/com/karumi/dexter/MultiplePermissionsReport.java (hunk 1 above)
Comment (pedrovgs) [reply dexter/src/main/java/com/karumi/dexter/MultiplePermissionsReport.java:37]: I used this one just in case the order was relevant to any user. For us it is not 😃
